export enum ActivityActionEnum {
  USER_REGISTER = 'USER_REGISTER',
  USER_LOGIN = 'USER_LOGIN',
  LOGIN_FAILED = 'LOGIN_FAILED',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  ADMIN_DELETED_USER = 'ADMIN_DELETED_USER',
  ADMIN_RESTORED_USER = 'ADMIN_RESTORED_USER',
}
